baseURL = "https://fdvdberg.netlify.app/"
languageCode = "en-us"
title = "Florem Ipsum"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#EEBC40"
    description = "Portfolio of Floris van den Berg, UX Writer"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "fdvandenberg@gmail.com"
    twitter = "floremipsum"
    linkedin = "https://www.linkedin.com/in/fdvandenberg"
    github = "fdvandenberg"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "floris.jpg"
    subtitle = "Hi! I'm Floris, a freelance UX Writer and Content Designer."
    hero_right = ["**Currently doing consultancy work at UX Society. Previously doing UX and product at Agoda in Bangkok, Thailand as an international intern.**", "I founded [User Experience Society](https://www.facebook.com/UXSoc/), the first student UX organization in the Philippines. For two years, we've had 20+ events with 30+ speakers for over 300 members and 500+ attendees. We've expanded to [California](https://www.facebook.com/profile.php?id=245708449193012) this year.", "I do a bit of writing as well. [Here's an article with a total of 21,000+ views to InVision & Medium](http://blog.invisionapp.com/ux-internship-wisdom/) talking about 50 things I learned spending 3 years as a UX intern.", "I help cultivate the design community in Manila too. I'm the youngest core member of [UX Philippines](https://www.facebook.com/groups/uxphilippines/) and I moderated a panel with some cool people for the [UXPH 2017 Conference](https://www.uxphilippines.com).", "I'm finishing my Bachelor's degree in Management Information Systems at the Ateneo de Manila University, expecting to graduate in 2018."]
    resume = "CV.pdf"

[params.process]
    enable = true
    title = "My Process"
    subtitle = "Full Process Design"

[params.case_studies]
    enable = true
    title = "My Portfolio"
    subtitle = "Selected Works"

[params.footer]
    enable = true
