baseURL = "https://fdvdberg.netlify.app/"
languageCode = "en-us"
title = "Florem Ipsum"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#EEBC40"
    description = "Portfolio of Floris van den Berg"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "fdvandenberg@gmail.com"
    twitter = "lexiscollado"
    dribbble = "alexiscollado"
    linkedin = "https://www.linkedin.com/in/alexander-hans-collado-jr-9444146a"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "/avatar.jpg"
    subtitle = "Hi! I'm Floris, a UX Writer & Content Creator."
    hero_right = ["**I am a Content Designer and UX Writer who’s obsessed with language and user understanding. I love solving complex problems, creating joyful experiences, and educating on brandvoice.**", "Currently I work as Lead Digital Copywriter at Allianz Direct, a new Pan-European Allianz label. I am in charge of interface copy and across all digital platforms. I own the writing process from end to end, collaborating with product owners, engineers, designers, and many others to bring user experiences to life. I write copy for a number of channels and formats such as website, portal, email, and online ads.", "I bring a lot of experience: for 15+ years I have worked at large advertising agencies and global brands, always creating impact through design and copy.", "**A data-driven idea generator.**", "Data is the foundation of everything I do. I love to combine insights with creativity. Note: I use data to touch, not to target people. I am very curious, want to know everything. What my fellow writers and designers are up to, but especially how I can help customers to get what they need. Truly ‘customer obsessed’.", "**A trusted part of your team.**", "You don't have time to mess around. You need someone who knows how to move people to action and get results that positively affect revenue, at every stage of the journey. These people trusted me to be that guy."]
    resume = "ResumeCollado.pdf"

[params.process]
    enable = true
    title = "My Services"
    subtitle = "Full Process Design"

[params.case_studies]
    enable = true
    title = "My Portfolio"
    subtitle = "Selected Works"

[params.footer]
    enable = true
